const FilterData = [
    { 
        field: "archetypePower",
        label: "Archetype of Power",
        suffixes: ["_in"],
        options: {
            "enchantress": 1394,
            "hag": 1772,
            "mage": 1729,
            "necromancer": 1592,
            "occultist": 1843,
            "seer": 1422,
            "witch of will": 1,
            "witch of wisdom": 1,
            "witch of wit": 1,
            "witch of woe": 1,
            "witch of wonder": 1
        },
    },
    { 
        field: "background",
        label: "Background",
        suffixes: ["_in"],
        options: {
            "dusty rose": 1,
            "lavender": 1353,
            "moss": 1044,
            "peach": 960,
            "pink": 1640,
            "plum": 1445,
            "rust": 798,
            "sage": 1,
            "sea": 1236,
            "sepia": 2,
            "taupe": 1277
        },
    },
    { 
        field: "backItem",
        label: "Back Item",
        suffixes: ["_in"],
        options: {
            "none" : 0,
            "arcane circuitry halo": 1,
            "chinese lantern": 1320,
            "lily": 1431,
            "mage aura (orange)": 94,
            "monstera": 1435,
            "scripted circle (blue)": 116,
            "scripted mage aura (blue)": 108,
            "scripted mage aura (gold)": 107,
            "scripted mage aura (green)": 102,
            "scripted mage aura (purple)": 113
        },
    },
    { 
        field: "bodyShape",
        label: "Body Shape",
        suffixes: ["_in"],
        options: {
            "chiseled": 3211,
            "lithe": 3807,
            "soft": 2739
        },
    },
    { 
        field: "earrings",
        label: "Earrings",
        suffixes: ["_in"],
        options: {
            "none" : 0,
            "basic piercings (silver)": 1485,
            "beaded tassel (emerald)": 91,
            "beaded tassel (ruby)": 96,
            "beaded tassel (sapphire)": 73,
            "bone hoops (gold)": 48,
            "bone hoops (silver)": 64,
            "dangly bones (bone)": 227,
            "demeulemeester (white)": 1,
            "ethereum hoops (silver)": 68,
            "fang charm (blue)": 38,
            "fang charm (red)": 62,
            "howl gems (green)": 59,
            "howl gems (orange)": 90,
            "howl gems (purple)": 86,
            "mandible cuffs (natural)": 56,
            "pearly skulls (silver)": 137,
            "piercing eye (blue)": 43,
            "piercing eye (green)": 30,
            "piercing eye (pink)": 34,
            "piercing eye (purple)": 33,
            "piercing eye (red)": 29
        }
    },
    {
        field: "eyebrows",
        label: "Eyebrows",
        suffixes: ["_in"],
        options: {
            "arched (brown)": 1174,
            "bushy (brown)": 1243,
            "bushy (white)": 1169,
            "fluffy (brown)": 1,
            "fluffy (white)": 1,
            "medium flat (black)": 1195,
            "pencil (white)": 1087,
            "pierced pyramid stud (grey)": 82,
            "pierced (white)": 87,
            "round (navy)": 1137,
            "starman (brown)": 1,
            "strong (black)": 1245,
            "sylv (white)": 1,
            "thin arched (grey)": 1206,
            "thin arched (teal)": 1
        },
    },
    { 
        field: "eyeColor",
        label: "Eye Color",
        suffixes: ["_in"],
        options: {
            "amber": 336,
            "amethyst": 1,
            "aqua": 173,
            "aquamarine": 1,
            "bicolor blue gold": 233,
            "bicolor pink turquoise": 232,
            "black": 93,
            "blank": 1,
            "blue": 212,
            "bronze": 65,
            "brown": 45,
            "carnelian": 301,
            "cloud": 1,
            "emerald": 33,
            "flooded aqua": 20,
            "flooded cobalt": 14,
            "flooded glo": 17,
            "flooded gold": 18,
            "flooded red": 9,
            "garnet": 1,
            "glo": 941,
            "gold": 1103,
            "green": 819,
            "grey": 1304,
            "grey green": 297,
            "hazel": 305,
            "lilac": 266,
            "opal": 139,
            "pink": 1053,
            "purple": 416,
            "red": 828,
            "ruby": 43,
            "silver": 10,
            "violet": 307,
            "void black": 53,
            "white": 66
        },
    },
    { 
        field: "eyeStyle",
        label: "Eye Style",
        suffixes: ["_in"],
        options: {
            "alert": 612,
            "aletheia": 1,
            "aradia": 1,
            "babylash": 1166,
            "blank": 299,
            "circle lens": 1910,
            "clear graphic": 191,
            "darkened demon bloom": 114,
            "demon": 85,
            "demon bloom": 45,
            "hooded side": 1462,
            "hypnotic": 326,
            "inscribed demon bloom": 34,
            "keridwen": 1,
            "liquid metal": 65,
            "liquid metal lined": 14,
            "nyx": 1,
            "reverse cateye": 377,
            "sclera": 190,
            "shadowed": 104,
            "smudged": 540,
            "smudged monolid": 224,
            "smudged snake": 713,
            "starman": 1,
            "sunset almond": 1185,
            "sylv": 1,
            "the stalk": 53,
            "the stalk lined": 40,
            "xuannu": 1
        },
    },
    { 
        field: "faceMarkings",
        label: "Face Markings",
        suffixes: ["_in"],
        options: {
            "none" : 0,
            "aradia (henna)": 1,
            "cheek and chin mole": 359,
            "cheekbone mole": 1,
            "cheek mole": 407,
            "claw marked (black)": 32,
            "claw marked (blue)": 12,
            "claw marked (purple)": 5,
            "claw marked (red)": 26,
            "daedra": 50,
            "eye of hinoto": 65,
            "freckles": 394,
            "horned moon markings (black)": 58,
            "horned moon markings (blue)": 7,
            "horned moon markings (purple)": 30,
            "horned moon markings (red)": 38,
            "mage mark moon (blue)": 25,
            "mage script daedric": 1,
            "mage script daedric (aqua)": 5,
            "mage script daedric (blue)": 3,
            "mage script daedric (gold)": 10,
            "mage script daedric (green)": 8,
            "mage script demonic (aqua)": 10,
            "mage script demonic (gold)": 18,
            "mage script demonic (green)": 22,
            "mage script demonic (phosphorescent)": 18,
            "mage script geometric (blue)": 22,
            "mage script helm (acqua)": 6,
            "mage script helm (aqua)": 7,
            "mage script helm (blue)": 3,
            "mage script helm (gold)": 17,
            "mage script helm (green)": 19,
            "mage script helm (purple)": 18,
            "mage script melovesmealot (blue)": 23,
            "mage script melovesmealot (gold)": 25,
            "mage script melovesmealot (green)": 18,
            "mage script melovesmealot (purple)": 14,
            "mage script serpent": 25,
            "mage script serpent (blue)": 13,
            "mage script serpent (green)": 15,
            "mage script serpent (phosphorescent)": 21,
            "mage script woods (blue)": 22,
            "mage script woods (gold)": 15,
            "mage script woods (green)": 18,
            "mage script woods (purple)": 20,
            "mangekyō markings (black)": 43,
            "mark of air (white)": 44,
            "mark of earth (white)": 41,
            "mark of leon": 4,
            "mark of moon tears (white)": 64,
            "mark of the chained moon (white)": 54,
            "mark of the damned": 51,
            "mark of the hierophant": 5,
            "mark of the mantis": 43,
            "mark of the wanderer": 16,
            "moon mark (white)": 55,
            "nega moon mark (black)": 33,
            "nega moon mark (white)": 1,
            "nose bridge scar": 381,
            "star mark (white)": 48,
            "starry blush (pink)": 3,
            "undereye gems (white)": 217
        },
    },
    { 
        field: "facewear",
        label: "Facewear",
        suffixes: ["_in"],
        options: {
            "none" : 0,
            "blindfold (aquamarine)": 18,
            "blindfold (indigo)": 22,
            "blindfold (maroon)": 17,
            "blindfold (night)": 65,
            "blindfold (royal)": 19,
            "blindfold (turmeric)": 20,
            "bridge piercing": 463,
            "eyepatch (black)": 42,
            "eyepatch (blue)": 41,
            "eyepatch (rose)": 74,
            "givenchy nosering (gold)": 51,
            "givenchy nosering (silver)": 88,
            "jeweled septum ring (blue)": 436,
            "labret (silver)": 440,
            "mage mark (solidity dragon scales)": 1,
            "mark of tacolin (silver)": 19,
            "moth gauze": 1,
            "pearl band (amethyst)": 1,
            "pearl circlet (garnet)": 1,
            "pearl veil": 51,
            "sad girl tears": 239,
            "scripted octagon glasses (blue)": 71,
            "scripted octagon glasses (green)": 64,
            "scripted octagon glasses (purple)": 56,
            "septum ring (turquoise)": 452,
            "simple octagon glasses (silver)": 208,
            "simple septum ring (silver)": 435,
            "swiss dot veil (black)": 86
        },
    },
    { 
        field: "foreheadJewelry",
        label: "Forehead Jewelry",
        suffixes: ["_in"],
        options: {
            "none" : 0,
            "astrea (gold)": 1,
            "curse tag": 1,
            "darkened demon third eye (glo)": 74,
            "darkened demon third eye (opal)": 88,
            "darkened demon third eye (ruby)": 80,
            "darkened demon third eye (sapphire)": 82,
            "demon third eye (black)": 102,
            "ethereum diadem (gold)": 29,
            "ethereum diadem (silver)": 229,
            "punks tiara (gold)": 58,
            "radiant third eye (blue)": 10,
            "radiant third eye (green)": 6,
            "radiant third eye (red)": 6,
            "raised third eye (blue)": 12,
            "raised third eye (gold)": 10,
            "raised third eye (green)": 31,
            "raised third eye (pink)": 67,
            "raised third eye (purple)": 33,
            "raised third eye (red)": 73,
            "rope third eye (blue)": 11,
            "rope third eye (green)": 20,
            "rope third eye (purple)": 27,
            "simple circlet (silver)": 43
        },
    },
    { 
        field: "hairBack",
        label: "Hair (Back)",
        suffixes: ["_in"],
        options: {
            "aletheia": 321,
            "aradia": 885,
            "box braid pony": 51,
            "bubble braids": 160,
            "calm pigtails": 235,
            "cloudy skies": 31,
            "curl cloud": 300,
            "cute pigtails": 287,
            "double locs": 58,
            "dramatic swoop": 426,
            "drill cloud": 161,
            "flowing pigtails": 172,
            "flowy pony": 833,
            "high blowout": 373,
            "jeweled hood": 108,
            "keridwen": 513,
            "low pony": 160,
            "miranda priestly": 15,
            "nyx long": 247,
            "puffy buns": 36,
            "sheer pearl veil": 55,
            "soft braid": 1111,
            "soft waves": 269,
            "wolf": 183,
            "xuannu": 227
        },
    },
    { 
        field: "hairFront",
        label: "Hair (Front)",
        suffixes: ["_in"],
        options: {
            "aletheia": 1179,
            "aradia": 646,
            "aradia short": 1208,
            "astrea": 1,
            "baby drill curls": 546,
            "bald": 196,
            "box braids": 274,
            "celestial blessing": 1,
            "cloudy skies": 31,
            "curl cloud": 732,
            "curtain": 811,
            "dramatic swoop": 426,
            "drill curls": 384,
            "gelled baby hair": 204,
            "hair wrap": 75,
            "high pony": 223,
            "jeweled hood": 54,
            "jeweled hood covered": 54,
            "jeweled turban": 52,
            "keridwen": 466,
            "miranda priestly": 127,
            "nyx": 425,
            "pixie": 110,
            "sheer pearl veil": 55,
            "starman": 1,
            "sylv": 1,
            "xuannu": 1475
        },
    },
    { 
        field: "hairMiddle",
        label: "Hair (Middle)",
        suffixes: ["_in"],
        options: {
            "cute buns": 365,
            "dark lady": 377,
            "double locs": 62,
            "flower buns": 20
        },
    },
    { 
        field: "hairColor",
        label: "Hair Color",
        suffixes: ["_in"],
        options: {
            "ash": 768,
            "auburn": 766,
            "black": 553,
            "blue": 18,
            "cyan": 9,
            "desert": 30,
            "emerald": 74,
            "ethereum": 19,
            "glo": 220,
            "green": 14,
            "iridescent": 55,
            "lavender": 730,
            "lilac": 751,
            "marine": 26,
            "mauve": 689,
            "mermaid": 768,
            "mint": 28,
            "navy": 667,
            "ochre": 13,
            "periwinkle": 12,
            "pink": 613,
            "platinum": 809,
            "plum": 37,
            "purple": 27,
            "roguish blonde": 1,
            "saffron": 24,
            "silver": 897,
            "steel": 868,
            "warm brown": 57,
            "white": 18
        },
    },
    { 
        field: "hairTopper",
        label: "Hair Topper",
        suffixes: ["_in"],
        options: {
            "none" : 0,
            "anemone horns": 88,
            "aries horns": 245,
            "bat wings": 787,
            "crown of pearls": 325,
            "feathered hairpins": 86,
            "gentle horns": 237,
            "hairpins": 1,
            "horns of taurus": 254,
            "jeweled antlers": 134,
            "leafy crown": 121,
            "maleficent horns": 267,
            "star circlet": 1
        },
    },
    { 
        field: "hat",
        label: "Hat",
        suffixes: ["_in"],
        options: {
            "none" : 0,
            "arcane stars (black)": 100,
            "chic disk (black)": 92,
            "dita disk (black)": 70,
            "dita disk with poppies": 52,
            "floral lacewing": 90,
            "hoodlondon hathor (gold)": 266,
            "lined (black)": 249,
            "many eyed hat": 41,
            "moon moth (black)": 75,
            "mushroom": 101,
            "proper witch": 45,
            "rounded lady": 27,
            "sheer moon nyx veil (purple)": 19,
            "sheer moon xuannu veil (purple)": 14,
            "straw circle": 53,
            "structured flowers (black)": 20,
            "sylv (black)": 1,
            "twin snakes": 34,
            "valkyrie dark": 28,
            "valkyrie light (white)": 23,
            "vogue witch": 25,
            "witch": 1154,
            "witch (black)": 2,
            "young floral horns": 80
        },
    },
    {
        field: "mask",
        label: "Mask",
        suffixes: ["_in"],
        options: {
            "none" : 0,
            "butterfly (emerald)": 45,
            "butterfly glasses (cyan)": 14,
            "butterfly glasses (pink)": 10,
            "butterfly (gold)": 53,
            "butterfly (rose quartz)": 45,
            "glowing phosphorous mask (aqua)": 15,
            "glowing phosphorous mask (purple)": 34,
            "gold veil (gold)": 24,
            "graceful bat": 65,
            "mage glass moon (blue)": 11,
            "mage glass moon (purple)": 14,
            "mage glass ribbon (blue)": 12,
            "mage glass ribbon (purple)": 7,
            "moth gauze (white)": 150,
            "yohji": 1
        },
    },
    { 
        field: "moonSign",
        label: "Moon Sign",
        suffixes: ["_in"],
        options: {
            "aquarius": 793,
            "aries": 780,
            "cancer": 857,
            "capricorn": 848,
            "gemini": 814,
            "leo": 789,
            "libra": 855,
            "pisces": 740,
            "sagittarius": 841,
            "scorpio": 825,
            "taurus": 838,
            "virgo": 777
        },
    },
    { 
        field: "mouth",
        label: "Mouth",
        suffixes: ["_in"],
        options: {
            "aletheia (mauve)": 1,
            "aradia (rose gold)": 1,
            "bow (brown)": 217,
            "bow (carnelian)": 1,
            "bow (coral)": 566,
            "bow (dusk)": 515,
            "bow (purple)": 762,
            "bow (red)": 767,
            "dark gloss (dark)": 477,
            "full pout (beige)": 262,
            "glossy medusa (natural)": 478,
            "keridwen (umber)": 1,
            "medusa (natural)": 196,
            "nyx (mocha)": 1,
            "parted (beige)": 861,
            "parted (black)": 831,
            "plump (black)": 214,
            "plump (natural)": 782,
            "punks cig (natural)": 31,
            "pursed (natural)": 227,
            "pursed (red)": 221,
            "round (dark)": 708,
            "round (red)": 339,
            "smirk (peach)": 1,
            "steady pout": 297,
            "thin smirk": 280,
            "thin smirk (orange)": 190,
            "witchy pout (black)": 527,
            "xuannu (cinnamon)": 1
        },
    },
    { 
        field: "necklace",
        label: "Necklace",
        suffixes: ["_in"],
        options: {
            "none" : 0,
            "astrea (gold)": 1,
            "chaotic howl stack (eclectic)": 55,
            "creepy yeha pearls (pearl)": 274,
            "eclectic choker stack (blue)": 79,
            "eclectic choker stack (green)": 97,
            "eclectic choker stack (purple)": 66,
            "eclectic choker stack (red)": 90,
            "ethereum thread (natural)": 133,
            "leather wrap (brown)": 1,
            "metal collar (silver)": 147,
            "moon choker (silver)": 131,
            "moon necklace (silver)": 326,
            "natural dried orange stack (natural)": 89,
            "pearl set (pearl)": 63,
            "piercing choker (blue)": 28,
            "piercing choker (green)": 39,
            "piercing choker (pink)": 25,
            "piercing choker (purple)": 40,
            "piercing choker (red)": 38,
            "ring collar (silver)": 39,
            "sacred cipher": 1,
            "stars thread (natural)": 82,
            "studded collar (silver)": 314,
            "thread necklace (natural)": 157
        },
    },
    { 
        field: "outerwear",
        label: "Outerwear",
        suffixes: ["_in"],
        options: {
            "none" : 0,
            "bone corset (black)": 83,
            "bone corset (white)": 85,
            "crochet (white)": 44,
            "feather robe (black)": 67,
            "feather robe (white)": 273,
            "school uniform (black)": 5
        },
    },
    { 
        field: "risingSign",
        label: "Rising Sign",
        suffixes: ["_in"],
        options: {
            "aquarius": 795,
            "aries": 797,
            "cancer": 812,
            "capricorn": 785,
            "gemini": 793,
            "leo": 840,
            "libra": 851,
            "pisces": 801,
            "sagittarius": 826,
            "scorpio": 823,
            "taurus": 817,
            "virgo": 817
        },
    },
    { 
        field: "skinTone",
        label: "Skin Tone",
        suffixes: ["_in"],
        options: {
            "dawn": 1508,
            "day": 1443,
            "dusk": 1302,
            "midnight": 1219,
            "night": 1330,
            "sunset": 1375,
            "twilight": 1580
        },
    },
    { 
        field: "sunSign",
        label: "Sun Sign",
        suffixes: ["_in"],
        options: {
            "aquarius": 832,
            "aries": 807,
            "cancer": 805,
            "capricorn": 758,
            "gemini": 814,
            "leo": 862,
            "libra": 784,
            "pisces": 761,
            "sagittarius": 794,
            "scorpio": 856,
            "taurus": 809,
            "virgo": 875
        },
    },
    { 
        field: "top",
        label: "Top",
        suffixes: ["_in"],
        options: {
            "astrea (red)": 1,
            "feathered cloak (gold)": 57,
            "feathered cloak (phoenix)": 42,
            "feathered cloak (red)": 67,
            "filmy edwardian (white)": 206,
            "fluffy shroud (white)": 268,
            "leather neck piece (black)": 326,
            "lined romantic puff (white)": 31,
            "lunar qipao (white)": 1,
            "mock neck (black)": 596,
            "moon bow (blue)": 33,
            "moon bow (green)": 26,
            "moon bow (red)": 25,
            "mugler collarbone cutout (black)": 643,
            "mugler slashed (black)": 200,
            "mugler tailored (black)": 226,
            "mugler tailored (white)": 221,
            "off shoulder (black)": 295,
            "open collar (black)": 1,
            "open collar (flint)": 1,
            "open collar with bow (black)": 263,
            "open collar with bow (white)": 274,
            "open collar with flowers (white)": 49,
            "pearl shawl": 103,
            "peter pan (white)": 211,
            "poet (white)": 207,
            "ragged shawl (black)": 496,
            "romantic puff (white)": 125,
            "sheer sleeves (black)": 353,
            "sheer striped (black)": 512,
            "sheer top (black)": 170,
            "shirt with tie (white)": 25,
            "shredded top (black)": 308,
            "shredded top (white)": 122,
            "shroud (dusk)": 318,
            "shroud (dusty rose)": 232,
            "shroud (lilac)": 349,
            "shroud (sage)": 169,
            "shroud (wisteria)": 180,
            "strappy crochet top": 53,
            "straps (black)": 844,
            "striped shroud (umber)": 549,
            "victorian frippery (white)": 99,
            "vivetta ghost hand collar (black)": 239,
            "vivetta hand collar (red)": 147,
            "wide collared shirt (white)": 98,
            "wispy robe (cinnamon)": 1
        },
    },
    {
        field: "wiles",
        label: "Wiles",
        suffixes: ["_gte","_lte"],
        options: [0, 10], // min and max values
    },
    {
        field: "will",
        label: "Will",
        suffixes: ["_gte","_lte"],
        options: [0, 10], // min and max values
    },
    {
        field: "wisdom",
        label: "Wisdom",
        suffixes: ["_gte","_lte"],
        options: [0, 10], // min and max values
    },
    {
        field: "wit",
        label: "Wit",
        suffixes: ["_gte","_lte"],
        options: [0, 10], // min and max values
    },
    {
        field: "woe",
        label: "Woe",
        suffixes: ["_gte","_lte"],
        options: [0, 10], // min and max values
    },
    {
        field: "wonder",
        label: "Wonder",
        suffixes: ["_gte","_lte"],
        options: [0, 10], // min and max values
    },
    {
        field: "attributeCount",
        label: "Attribute Count",
        suffixes: ["_gte","_lte"],
        options: [0, 100], // min and max values
    },
]

export default FilterData